language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
script:
  - 'npm run lint'
  - 'npm run test'
  - 'npm run build'
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
